version: '3.8'

services:
  web:
    build: .
    container_name: exam-form-app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    restart: unless-stopped
    networks:
      - exam-network

networks:
  exam-network:
    driver: bridge